apiVersion: v1
kind: Pod
metadata:
        name: single
        labels:
                env: test
spec:
        containers:
                - name: c6
                  image: nginx
---
apiVersion: v1
kind: Service
metadata:
        name: lbservice
spec:
        selector:
                env : test
        type: LoadBalancer
        ports:
                - port :  80
                  targetPort: 80

