apiVersion: v1
kind: Pod
metadata:
        name: secretpod
spec:
        containers:
                - name : c1
                  image: centos:6
                  command: [/bin/sh,-c,'while true; do echo hello; sleep 1; done']
                  env:
                          - name: password
                            valueFrom:
                                    secretKeyRef:
                                            key: secret
                                            name: token1
