apiVersion: batch/v1
kind: Job
metadata:
        name: onejob
spec:
        parallelism: 2
        completions: 8
        template:
                spec:
                        containers:
                                - name: j1
                                  image: centos:6
                                  command: [/bin/sh,-c,sleep 5]
                        restartPolicy: Never          
                               

