apiVersion: v1
kind: Pod
metadata:
        name: emppods
spec:
        containers:
                - name: c1
                  image: nginx
                  volumeMounts:
                          - name: empvol
                            mountPath: /usr/share/nginx/html/
                - name: c2
                  image: centos:6
                  command: [/bin/sh,-c,'while true; do X=$[$X+1]; echo $X > /usr/share/nginx/html/index.html;sleep 1; done']
                  volumeMounts:
                          - name: empvol
                            mountPath: /usr/share/nginx/html
        volumes:
                - name : empvol
                  emptyDir: {}


