apiVersion: v1
kind: Pod
metadata:
        name: hostpods
spec:
        containers:
                - name: c1
                  image: nginx
                  volumeMounts:
                          - name: hostvol
                            mountPath: /usr/share/nginx/html/
                - name: c2
                  image: centos:6
                  command: [/bin/sh,-c,'while true; do X=$[$X+1]; echo $X >> /usr/share/nginx/html/index.html;sleep 1; done']
                  volumeMounts:
                          - name: hostvol
                            mountPath: /usr/share/nginx/html
        volumes:
                - name : hostvol
                  hostPath: gke-madhurid-cluster-default-pool-d18a543c-6wlt 


