apiVersion: v1
kind: Pod
metadata:
        name: pvpod
spec:
        containers:
                - name: p1
                  image: mongo
                  volumeMounts:
                          - name: pvvol
                            mountPath: /data/db
                   ports:
                           - containerPort: 27017
         volumes:
                 - name: pvvol
                   gcePersistentDisk: 
                   pdName: madhurid-pvdisk
                   fsType: ext4

